version: "3.9"

services:
  api:
    build: .
    container_name: job_api
    env_file:
      - ./.env  
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app/app
    environment:
      - DEBUG=1
    restart: always